class Storyteller:
    @staticmethod
    def create_narrative(insights, dataset_name, stats_summary):
        """Create structured narrative report"""
        
        narrative = f"""
# 📊 Data Story: {dataset_name}

## Executive Summary
{insights[:500] if insights else "Analysis complete. Key patterns identified in the visualizations below."}

## Key Metrics at a Glance
{stats_summary}

## What This Means
The data reveals opportunities for data-driven decision making. 
Review each visualization for specific insights related to distributions, 
relationships, and trends in your data.

## Next Steps
1. **Explore** the interactive charts to understand patterns
2. **Identify** which metrics matter most to your goals
3. **Act** on the recommendations provided
4. **Monitor** changes over time with updated data

---
*This report was automatically generated by AI Analytics Engine*
"""
        return narrative